### ISSUE TITLE
DM: Define measuring user experience

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#105]
## Purpose
To understand of impact of improvements, user research needed, priority of features and continuous improvement of the product experience.

## Notes

**Resources:**

- Stakeholder interview
- Comparative analysis - common self service features
- [Delivering a digital first public experience](https://www.whitehouse.gov/omb/management/ofcio/delivering-a-digital-first-public-experience/)
- [FAS UX Strategy (template)](https://docs.google.com/document/d/1kJ8KzVeOhKni1KqntWYHJCwOcmhEgWdliF2dXxztGkQ/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/cg-ui/issues/109
- [ ] https://github.com/cloud-gov/product/issues/2926
- [ ] Recommendation for additional UX research
```

**Comment by echappen** [comment]
Closing as outdated
