### ISSUE TITLE
DM: Define login and add user

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#106]
### Design Milestone: DM: Define login and add user

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/cg-ui/issues/128
- [ ] https://github.com/cloud-gov/cg-ui/issues/112
- [ ] https://github.com/cloud-gov/cg-ui/issues/107
```
