### ISSUE TITLE
Round 1: Design testing and customer research

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#107]
**Research goals:**
- Usability testing of current state
- Usability testing of wireframes / design flow
- Questions on desired features 

**8-10 participants**

**Acceptance criteria**
- [ ] Update journey 1 wireframes based on feedback
- [ ] Synthesis of research

** Issues **

- [ ] Create a research plan (issue forthcoming)
```[tasklist]
### Tasks
- [ ] prototype manage user
- [ ] create research plan
- [ ] recruiting
```

**Comment by echappen** [comment]
Closing as outdated
