### ISSUE TITLE
DM: Suggested product feature list and priorities for product roadmap

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#108]
### DM: Suggested product feature list and priorities for product roadmap

- [x] Understand feature parity with Stratos - what needs to be in MVP that's currently accessible
- [x] Additional needed and desirable features

### Acceptance criteria
- [x] Feature list: categorized by for MVP/Foundational or after: [Features for foundational build here](https://docs.google.com/document/d/1p1kFY1AUnR5OqtQYBgUFVPeKxZimbC-0qsdSgwARFco/edit#heading=h.z0m9c73nd3q7)
- [x] Preliminary features selected for foundational build and priority: 1. Manager users, 2. View apps, 3. Billing & management 4. Logs
