### ISSUE TITLE
0D. Navigation design and growth strategy

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#122]
Investigate navigation needs. Sketch and document possible navigation flows accounting for growth and possible future needs. 
- [x] Discovery
- [x] Initial sketches

### Acceptance criteria:
- [ ] feasibility review/co-work of sketches
- [ ] PO review of sketches

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/cg-ui/issues/170
```

**Comment by echappen** [comment]
Superseded by #341
