### ISSUE TITLE
EPIC: 1. Manage users - Layout

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#227]
Layout supporting all user stories for Manage users

### Steps to delivery (an iterations definition of done)
- [x] design & define layout for manage users view all
  - [ ] initial breakdown into components
- [x] feasibility review/co-work
- [ ] product review: place in ready for build, prioritize if needed
- [ ] build
- [ ] user testing

## User stories (components)
User story [epic]: As an org manager, for an org, I can:
- quickly find a user and their org roles, assigned spaces, and space role
- view all users and info: 
  - email address #190 
  - assigned org roles assigned #189 
  - assigned spaces and roles #219 
  - last logged in day and time #220 
    - option to resend email invite and register if needed #228
- add a user to an org so they can access the org’s platform #229
- set and edit a user’s permissions (role) for an org #210 
- add and remove a user to one or more spaces #221
- set and edit a user's permission for a space 
-remove a user from an org #215 

## For build
[Layout breakdown in Figma](https://www.figma.com/design/uU63HcBZQfAjx1OJuY0yti/Cloud.gov---Wireframes?node-id=1256%3A39481&t=Qdaz0tK332DBhy32-1)

**User story:** 

### Acceptance criteria
**Accessibility:**
- [ ] passes Section 508 compliance
