### ISSUE TITLE
Story: User can log in and out of the app

### ISSUE THREAD

**Issue by chizo-gov** [cloud-gov/cg-ui#495]
### Why 

**As a a user, I need to** log in and out of the app, **so I can** access my information and keep my information secure when not in use. 

### Acceptance Criteria

- [ ] xx
- [ ] xx
- [ ] xx

#### Scenario 

- **Given**: xx
- **When**: xx
- **Then**: xx

```[tasklist]
### Tasks for implementing this story
- [ ] #112 
- [ ] https://github.com/cloud-gov/cg-ui/issues/46
- [ ] https://github.com/cloud-gov/cg-ui/issues/29
- [ ] https://github.com/cloud-gov/cg-ui/pull/57
- [ ] https://github.com/cloud-gov/cg-ui/issues/22
- [ ] https://github.com/cloud-gov/cg-ui/issues/21
- [ ] https://github.com/cloud-gov/cg-ui/issues/20
- [ ] https://github.com/cloud-gov/cg-ui/issues/14
- [ ] https://github.com/cloud-gov/cg-ui/issues/15
- [ ] https://github.com/cloud-gov/cg-ui/issues/9
- [ ] https://github.com/cloud-gov/cg-ui/issues/163
- [ ] https://github.com/cloud-gov/cg-ui/issues/160
- [ ] https://github.com/cloud-gov/cg-ui/issues/494
```

```[tasklist]
### Dependencies that need to be resolved before starting or completing this story
- [ ] 

```
