### ISSUE TITLE
Story: User can add and remove a user to one or more spaces and set space roles

### ISSUE THREAD

**Issue by chizo-gov** [cloud-gov/cg-ui#512]
### Why 

**As a user, I need to** add and remove a user to one more more spaces and set spaces roles.

### Acceptance Criteria

- [ ] xx
- [ ] xx

```[tasklist]
### Tasks to complete this story
- [ ] https://github.com/cloud-gov/cg-ui/issues/468
- [ ] https://github.com/cloud-gov/cg-ui/issues/219
- [ ] https://github.com/cloud-gov/cg-ui/issues/221
- [ ] https://github.com/cloud-gov/cg-ui/issues/312
- [ ] https://github.com/cloud-gov/cg-ui/issues/230
```
