### ISSUE TITLE
UX Research: Round 1

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#68]
## Round 1
- [Research plan](https://docs.google.com/document/d/1SbF4iVOD0iby3YtlM0rq0qTdn82yEATc7gc0b0yqMMU/edit#heading=h.x23pmmz9qr8b)
- [Interview guide](https://docs.google.com/document/d/1dOng4PWlOi93vg39c_sT5Y4ZnAfvR-ZQ0VWxFaX6-rE/edit)
- [Synthesis Airtable](https://airtable.com/appGN4pCRWeMrFagx/tblrvmRICA7OxdRed/viwA5kRxGNYcwxUkR?blocks=hide)

### Goals
- Understand current experience and user needs / jobs to be done
- Get feedback on prototype of manage users page in the app

```[tasklist]
### Tasks
- [x] Create research plan
- [x] Recruit participants and schedule sessions
- [x] Draft interview questions
- [x] Conduct sessions
- [x] Synthesize findings
- [x] Discuss findings as a team and identify next steps
```
