### ISSUE TITLE
Milestone: User Management UI Layout

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#95]
```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/cg-ui/issues/100
- [ ] https://github.com/cloud-gov/cg-ui/issues/96
- [ ] https://github.com/cloud-gov/cg-ui/issues/98
- [ ] https://github.com/cloud-gov/cg-ui/issues/99
- [ ] https://github.com/cloud-gov/cg-ui/issues/97
```
